<!DOCTYPE html>
<html>
    <head>
        <title>Chap. 8</title>
    </head>
    <body>
        <h3 id="VIII">Le Saut De La Chapelle</h3>
<div class="exergue"><div>
<p>Qui voit son cors et sa façon,<br />
Trop par avroit le cuer felon<br />
Qui nen avroit d’Iseut pitié.
</p>
</div><div class="exergue_ref">(Béroul.)</div></div>
<p id="Bed_Tri_8.001">Par la cité, dans la nuit noire, la nouvelle court&#160;: Tristan et la reine ont été saisis&#160;; le roi veut les tuer. Riches bourgeois et petites gens, tous pleurent.</p>
<p id="Bed_Tri_8.002">«&#160;Hélas&#160;! Nous devons bien pleurer&#160;! Tristan, hardi baron, mourrez-vous donc par si laide traîtrise&#160;? Et vous, reine franche, reine honorée, en quelle terre naîtra jamais fille de roi si belle, si chère&#160;? C’est donc là, nain bossu, l’œuvre de tes devinailles&#160;? Qu’il ne voie jamais la face de Dieu, celui qui, t’ayant trouvé, n’enfoncera pas son épieu dans ton corps&#160;! Tristan, bel ami&#32;<span><span class="pagenum ws-pagenum" id="120" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/130"></span></span>cher, quand le Morholt, venu pour ravir nos enfants, prit terre sur ce rivage, nul de nos barons n’osa s’armer contre lui, et tous se taisaient, pareils à des muets. Mais vous, Tristan, vous avez fait le combat pour nous tous, hommes de Cornouailles, et vous avez tué le Morholt&#160;; et lui vous navra d’un épieu dont vous avez manqué mourir pour nous. Aujourd’hui, en souvenir de ces choses, devrions-nous consentir à votre mort&#160;?&#160;»</p>
<p id="Bed_Tri_8.003">Les plaintes, les cris, montent par la cité&#160;; tous courent au palais. Mais tel est le courroux du roi qu’il n’y a si fort et si fier baron qui ose risquer une seule parole pour le fléchir.</p>
<p id="Bed_Tri_8.004">Le jour approche, la nuit s’en va. Avant le soleil levé, Marc chevauche hors de la ville, au lieu où il avait coutume de tenir ses plaids et de juger. Il commande qu’on creuse une fosse en terre et qu’on y amasse des sarments noueux et tranchants et des épines blanches et noires, arrachées avec leurs racines.&#32;<span><span class="pagenum ws-pagenum" id="121" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/131"></span></span></p>
<p id="Bed_Tri_8.005">À l’heure de prime, il fait crier un ban par le pays pour convoquer aussitôt les hommes de Cornouailles. Ils s’assemblent à grand bruit&#160;: nul qui ne pleure, hormis le nain de Tintagel. Alors le roi leur parla ainsi&#160;:</p>
<p id="Bed_Tri_8.006">«&#160;Seigneurs, j’ai fait dresser ce bûcher d’épines pour Tristan et pour la reine, car ils ont forfait.&#160;»</p>
<p id="Bed_Tri_8.007">Mais tous lui crièrent&#160;:</p>
<p id="Bed_Tri_8.008">«&#160;Jugement, roi&#160;! le jugement d’abord, l’escondit et le plaid&#160;! Les tuer sans jugement, c’est honte et crime. Roi, répit et merci pour eux&#160;!&#160;»</p>
<p id="Bed_Tri_8.009">Marc répondit en sa colère&#160;:</p>
<p id="Bed_Tri_8.010">«&#160;Non, ni répit, ni merci, ni plaid, ni jugement&#160;! Par ce Seigneur qui créa le monde, si nul m’ose encore requérir de telle chose, il brûlera le premier sur ce brasier&#160;!&#160;»</p>
<p id="Bed_Tri_8.011">Il ordonne qu’on allume le feu et qu’on aille quérir au château Tristan d’abord.</p>
<p id="Bed_Tri_8.012">Les épines flambent, tous se taisent, le roi attend.&#32;<span><span class="pagenum ws-pagenum" id="122" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/132"></span></span></p>
<p id="Bed_Tri_8.013">Les valets ont couru jusqu’à la chambre où les amants sont étroitement gardés. Ils entraînent Tristan par ses mains liées de cordes. Par Dieu&#160;! ce fut vilenie de l’entraver ainsi&#160;! Il pleure sous l’affront&#160;; mais de quoi lui servent ses larmes&#160;? On l’emmène honteusement&#160;; et la reine s’écrie, presque folle d’angoisse&#160;:</p>
<p id="Bed_Tri_8.014">«&#160;Être tuée, ami, pour que vous soyez sauvé, ce serait grande joie&#160;!&#160;»</p>
<p id="Bed_Tri_8.015">Les gardes et Tristan descendent hors de la ville, vers le bûcher. Mais, derrière eux, un cavalier se précipite, les rejoint, saute à bas du destrier encore courant&#160;: c’est Dinas, le bon sénéchal. Au bruit de l’aventure, il s’en venait de son château de Lidan, et l’écume, la sueur et le sang ruisselaient aux flancs de son cheval&#160;:</p>
<p id="Bed_Tri_8.016">«&#160;Fils, je me hâte vers le plaid du roi. Dieu m’accordera peut-être d’y ouvrir tel conseil qui vous aidera tous deux&#160;; déjà il me permet du moins de te servir par une menue courtoisie. Amis, dit-il aux valets, je veux que vous le meniez sans ces &#32;<span><span class="pagenum ws-pagenum" id="123" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/133"></span></span>entraves, — et Dinas trancha les cordes honteuses&#160;; — s’il essayait de fuir, ne tenez-vous pas vos épées&#160;?&#160;»</p>
<p id="Bed_Tri_8.017">Il baise Tristan sur les lèvres, remonte en selle, et son cheval l’emporte.</p>
<p id="Bed_Tri_8.018">Or, écoutez comme le Seigneur Dieu est plein de pitié. Lui, qui ne veut pas la mort du pécheur, il reçut en gré les larmes et la clameur des pauvres gens qui le suppliaient pour les amants torturés. Près de la route où Tristan passait, au faîte d’un roc et tournée vers la bise, une chapelle se dressait sur la mer.</p>
<p id="Bed_Tri_8.019">Le mur du chevet était posé au ras d’une falaise, haute, pierreuse, aux escarpements aigus&#160;; dans l’abside, sur le précipice, était une verrière, œuvre habile d’un saint. Tristan dit à ceux qui le menaient&#160;:</p>
<p id="Bed_Tri_8.020">«&#160;Seigneurs, voyez cette chapelle&#160;; permettez que j’y entre. Ma mort est prochaine, je prierai Dieu qu’il ait merci de moi, qui l’ai tant offensé. Seigneurs, la chapelle n’a d’autre issue que celle-ci&#160;; chacun de vous&#32;<span><span class="pagenum ws-pagenum" id="124" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/134"></span></span>tient son épée&#160;; vous savez bien que je ne puis passer que par cette porte, et quand j’aurai prié Dieu, il faudra bien que je me remette entre vos mains&#160;!&#160;»</p>
<p id="Bed_Tri_8.021">L’un des gardes dit&#160;:</p>
<p id="Bed_Tri_8.022">«&#160;Nous pouvons bien le lui permettre.&#160;»</p>
<p id="Bed_Tri_8.023">Ils le laissèrent entrer. Il court par la chapelle, franchit le chœur, parvient à la verrière de l’abside, saisit la fenêtre, l’ouvre et s’élance… Plutôt cette chute que la mort sur le bûcher, devant telle assemblée&#160;!</p>
<p id="Bed_Tri_8.024">Mais sachez, seigneurs, que Dieu lui fit belle merci&#160;; le vent se prend en ses vêtements, le soulève, le dépose sur une large pierre au pied du rocher. Les gens de Cornouailles appellent encore cette pierre le «&#160;Saut de Tristan&#160;».</p>
<p id="Bed_Tri_8.025">Et devant l’église les autres l’attendaient toujours. Mais pour néant, car c’est Dieu maintenant qui l’a pris en sa garde. Il fuit&#160;: le sable meuble croule sous ses pas. Il tombe, se retourne, voit au loin le bûcher&#160;: la flamme bruit, la fumée monte. Il fuit.&#32;<span><span class="pagenum ws-pagenum" id="125" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/135"></span></span></p>
<p id="Bed_Tri_8.026">L’épée ceinte, à bride abattue, Gorvenal s’était échappé de la cité&#160;: le roi l’aurait fait brûler en place de son seigneur. Il rejoignit Tristan sur la lande, et Tristan s’écria&#160;:</p>
<p id="Bed_Tri_8.027">«&#160;Maître&#160;! Dieu m’a accordé sa merci. Ah&#160;! chétif, à quoi bon&#160;? Si je n’ai Iseut, rien ne me vaut. Que ne me suis-je plutôt brisé dans ma chute&#160;! J’ai échappé, Iseut, et l’on va te tuer. On la brûle pour moi&#160;; pour elle je mourrai aussi.&#160;»</p>
<p id="Bed_Tri_8.028">Gorvenal lui dit&#160;:</p>
<p id="Bed_Tri_8.029">«&#160;Beau sire, prenez réconfort, n’écoutez pas la colère. Voyez ce buisson épais, enclos d’un large fossé&#160;; cachons-nous là&#160;: les gens passent nombreux sur cette route&#160;; ils nous renseigneront, et, si l’on brûle Iseut, fils, je jure par Dieu, le fils de Marie, de ne jamais coucher sous un toit jusqu’au jour où nous l’aurons vengée.</p>
<p id="Bed_Tri_8.030">— Beau maître, je n’ai pas mon épée.</p>
<p id="Bed_Tri_8.031">— La voici, je te l’ai apportée.</p>
<p id="Bed_Tri_8.032">— Bien, maître&#160;; je ne crains plus rien, fors Dieu.&#32;<span><span class="pagenum ws-pagenum" id="126" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/136"></span></span></p>
<p id="Bed_Tri_8.033">— Fils, j’ai encore sous ma gonelle telle chose qui te réjouira&#160;: ce haubert solide et léger, qui pourra te servir.</p>
<p id="Bed_Tri_8.034">— Donne, beau maître. Par ce Dieu en qui je crois, je vais maintenant délivrer mon amie.</p>
<p id="Bed_Tri_8.035">— Non, ne te hâte point, dit Gorvenal. Dieu sans doute te réserve quelque plus sûre vengeance. Songe qu’il est hors de ton pouvoir d’approcher du bûcher&#160;; les bourgeois l’entourent et craignent le roi&#160;: tel voudrait bien ta délivrance, qui, le premier, te frappera. Fils, on dit bien&#160;: Folie n’est pas prouesse… Attends…&#160;»</p>
<p id="Bed_Tri_8.036">Or, quand Tristan s’était précipité de la falaise, un pauvre homme de la gent menue l’avait vu se relever et fuir. Il avait couru vers Tintagel et s’était glissé jusqu’en la chambre d’Iseut&#160;:</p>
<p id="Bed_Tri_8.037">«&#160;Reine, ne pleurez plus. Votre ami s’est échappé&#160;!</p>
<p id="Bed_Tri_8.038">— Dieu, dit-elle, en soit remercié&#160;! Maintenant, qu’ils me lient ou me délient, qu’ils&#32;<span><span class="pagenum ws-pagenum" id="127" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/137"></span></span>m’épargnent ou qu’ils me tuent, je n’en ai plus souci&#160;!&#160;»</p>
<p id="Bed_Tri_8.039">Or, les félons avaient si cruellement serré les cordes de ses poignets que le sang jaillissait. Mais souriante, elle dit&#160;:</p>
<p id="Bed_Tri_8.040">«&#160;Si je pleurais pour cette souffrance, alors qu’en sa bonté Dieu vient d’arracher mon ami à ces félons, certes, je ne vaudrais guère&#160;!&#160;»</p>
<p id="Bed_Tri_8.041">Quand la nouvelle parvint au roi que Tristan s’était échappé par la verrière, il blêmit de courroux et commanda à ses hommes de lui amener Iseut.</p>
<p id="Bed_Tri_8.042">On l’entraîne&#160;; hors de la salle, sur le seuil, elle apparaît&#160;; elle tend ses mains délicates, d’où le sang coule. Une clameur monte par la rue&#160;: «&#160;Ô Dieu, pitié pour elle&#160;! Reine franche, reine honorée, quel deuil ont jeté sur cette terre ceux qui vous ont livrée&#160;! Malédiction sur eux&#160;!&#160;»</p>
<p id="Bed_Tri_8.043">La reine est traînée jusqu’au bûcher d’épines, qui flambe. Alors, Dinas, seigneur de Lidan, se laissa choir aux pieds du roi&#160;:</p>
<p id="Bed_Tri_8.044">«&#160;Sire, écoute-moi&#160;; je t’ai servi &#32;<span><span class="pagenum ws-pagenum" id="128" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/138"></span></span>longuement, sans vilenie, en loyauté, sans en retirer nul profit&#160;: car il n’est pas un pauvre homme, ni un orphelin, ni une vieille femme, qui me donnerait un denier de ta sénéchaussée, que j’ai tenue toute ma vie. En récompense, accorde-moi que tu recevras la reine à merci. Tu veux la brûler sans jugement&#160;: c’est forfaire, puisqu’elle ne reconnaît pas le crime dont tu l’accuses. Songes-y, d’ailleurs. Si tu brûles son corps, il n’y aura plus de sûreté sur ta terre&#160;: Tristan s’est échappé&#160;; il connaît bien les plaines, les bois, les gués, les passages, et il est hardi. Certes, tu es son oncle, et il ne s’attaquera pas à toi&#160;; mais tous les barons, tes vassaux, qu’il pourra surprendre, il les tuera.&#160;»</p>
<p id="Bed_Tri_8.045">Et les quatre félons pâlissent à l’entendre&#160;: déjà ils voient Tristan embusqué, qui les guette.</p>
<p id="Bed_Tri_8.046">«&#160;Roi, dit le sénéchal, s’il est vrai que je t’ai bien servi toute ma vie, livre-moi Iseut&#160;; je répondrai d’elle comme son garde et son garant.&#160;»&#32;<span><span class="pagenum ws-pagenum" id="129" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/139"></span></span></p>
<p id="Bed_Tri_8.047">Mais le roi prit Dinas par la main et jura par le nom des saints qu’il ferait immédiate justice.</p>
<p id="Bed_Tri_8.048">Alors Dinas se releva&#160;:</p>
<p id="Bed_Tri_8.049">«&#160;Roi, je m’en retourne à Lidan et je renonce à votre service.&#160;»</p>
<p id="Bed_Tri_8.050">Iseut lui sourit tristement. Il monte sur son destrier et s’éloigne, marri et morne, le front baissé.</p>
<p id="Bed_Tri_8.051">Iseut se tient debout devant la flamme. La foule, à l’entour, crie, maudit le roi, maudit les traîtres. Les larmes coulent le long de sa face. Elle est vêtue d’un étroit bliaut gris, où court un filet d’or menu&#160;; un fil d’or est tressé dans ses cheveux, qui tombent jusqu’à ses pieds. Qui pourrait la voir si belle sans la prendre en pitié aurait un cœur de félon. Dieu&#160;! comme ses bras sont étroitement liés&#160;!</p>
<p id="Bed_Tri_8.052">Or, cent lépreux, déformés, la chair rongée et toute blanchâtre, accourus sur leurs béquilles au claquement des crécelles, se pressaient devant le bûcher, et, sous leurs&#32;<span><span class="pagenum ws-pagenum" id="130" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/140"></span></span>paupières enflées leurs yeux sanglants jouissaient du spectacle.</p>
<p id="Bed_Tri_8.053">Yvain, le plus hideux des malades, cria au roi d’une voix aiguë&#160;;</p>
<p id="Bed_Tri_8.054">«&#160;Sire, tu veux jeter ta femme en ce brasier&#160;; c’est bonne justice, mais trop brève. Ce grand feu l’aura vite brûlée, ce grand vent aura vite dispersé sa cendre. Et, quand cette flamme tombera tout à l’heure, sa peine sera finie. Veux-tu que je t’enseigne pire châtiment, en sorte qu’elle vive, mais à grand déshonneur, et toujours souhaitant la mort&#160;? Roi, le veux-tu&#160;?&#160;»</p>
<p id="Bed_Tri_8.055">Le roi répondit&#160;:</p>
<p id="Bed_Tri_8.056">«&#160;Oui, la vie pour elle, mais à grand déshonneur et pire que la mort… Qui m’enseignera un tel supplice, je l’en aimerai mieux.</p>
<p id="Bed_Tri_8.057">— Sire, je dirai donc brièvement ma pensée. Vois, j’ai là cent compagnons. Donne-nous Iseut, et qu’elle nous soit commune&#160;! Le mal attise nos désirs. Donne-la à tes lépreux, jamais dame n’aura fait pire fin. Vois, nos haillons sont collés à nos plaies,&#32;<span><span class="pagenum ws-pagenum" id="131" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/141"></span></span>qui suintent. Elle qui, près de toi, se plaisait aux riches étoffes fourrées de vair, aux joyaux, aux salles parées de marbre, elle qui jouissait des bons vins, de l’honneur, de la joie, quand elle verra la cour de tes lépreux, quand il lui faudra entrer sous nos taudis bas et coucher avec nous, alors Iseut la Belle, la Blonde, reconnaîtra son péché et regrettera ce beau feu d’épines&#160;!&#160;»</p>
<p id="Bed_Tri_8.058">Le roi l’entend, se lève, et longuement reste immobile. Enfin, il court vers la reine et la saisit par la main. Elle crie&#160;:</p>
<p id="Bed_Tri_8.059">«&#160;Par pitié, sire, brûlez-moi plutôt, brûlez-moi&#160;!&#160;»</p>
<p id="Bed_Tri_8.060">Le roi la livre. Yvain la prend et les cent malades se pressent autour d’elle. À les entendre crier et glapir, tous les cœurs se fondent de pitié&#160;; mais Yvain est joyeux&#160;; Iseut s’en va, Yvain l’emmène. Hors de la cité descend le hideux cortège.</p>
<p id="Bed_Tri_8.061">Ils ont pris la route où Tristan est s’embusqué. Gorvenal jette un cri&#160;:</p>
<p id="Bed_Tri_8.062">«&#160;Fils, que feras-tu&#160;? Voici ton amie&#160;!&#160;»</p>
<p id="Bed_Tri_8.063">Tristan pousse son cheval hors du fourré&#160;:&#32;<span><span class="pagenum ws-pagenum" id="132" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/142"></span></span></p>
<p id="Bed_Tri_8.064">«&#160;Yvain, tu lui as assez longtemps fait compagnie&#160;; laisse-la maintenant, si tu veux vivre&#160;!&#160;»</p>
<p id="Bed_Tri_8.065">Mais Yvain dégrafe son manteau.</p>
<p id="Bed_Tri_8.066">«&#160;Hardi, compagnons&#160;! À vos bâtons&#160;! À vos béquilles&#160;! C’est l’instant de montrer sa prouesse&#160;!&#160;»</p>
<p id="Bed_Tri_8.067">Alors il fit beau voir les lépreux rejeter leurs chapes, se camper sur leurs pieds malades, souffler, crier, brandir leurs béquilles&#160;: l’un menace et l’autre grogne. Mais il répugnait à Tristan de les frapper&#160;; les conteurs prétendent que Tristan tua Yvain&#160;: c’est dire vilenie&#160;; non, il était trop preux pour occire telle engeance. Mais Gorvenal ayant arraché une forte pousse de chêne, l’asséna sur le crâne d’Yvain&#160;; le sang noir jaillit et coula jusqu’à ses pieds difformes.</p>
<p id="Bed_Tri_8.068">Tristan reprit la reine&#160;: désormais, elle ne sent plus nul mal. Il trancha les cordes de ses bras, et quittant la plaine, ils s’enfoncèrent dans la forêt du Morois. Là, dans les grands bois, Tristan se sent en sûreté&#32;<span><span class="pagenum ws-pagenum" id="133" title="Page:Le Roman de Tristan et Iseut, renouvelé par J. Bédier.djvu/143"></span></span>comme derrière la muraille d’un fort château.</p>
<p id="Bed_Tri_8.069">Quand le soleil pencha, ils s’arrêtèrent tous trois au pied d’un mont&#160;; la peur avait lassé la reine&#160;; elle reposa sa tête sur le corps de Tristan et s’endormit.</p>
<p id="Bed_Tri_8.070">Au matin, Gorvenal déroba à un forestier son arc et deux flèches bien empennées et barbelées et les donna à Tristan, le bon archer, qui surprit un chevreuil et le tua. Gorvenal fit un amas de branches sèches, battit le fusil, fit jaillir l’étincelle et alluma un grand feu pour cuire la venaison&#160;; Tristan coupa des branchages, construisit une hutte et la recouvrit de feuillée&#160;; Iseut la joncha d’herbes épaisses.</p>
<p id="Bed_Tri_8.071">Alors, au fond de la forêt sauvage, commença pour les fugitifs l’âpre vie, aimée pourtant.&#32;</p>
    </body>
</html>